# Python oriented pre-commit
#
# Note that the check-yaml argument does not work
#
# so only single document in a yaml file is allowed
# tried dockerfilelint but too strict and disabling does not work
---
# python regex syntax for inclusion
# https://www.w3schools.com/python/python_regex.asp
# So this means only look at python files
#files: ".py$"
# This is only for python and other files
# This means exclude directories ./typescript
#exclude: "typescript|golang"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    # temp fix for pre-commit breakage in shellcheck
    # https://github.com/jumanjihouse/pre-commit-hooks/issues/82
    rev: 2.1.5
    hooks:
      # as of Feb 2020, error with ruby 3.0
      # https://github.com/jumanjihouse/pre-commit-hooks/issues/86
      #- id: markdownlint
      - id: shellcheck
      - id: shfmt

  - repo: local
    hooks:
      # https://github.com/markdownlint/markdownlint/blob/master/.pre-commit-hooks.yaml
      - id: markdownlintlocal
        name: Markdownlint Local
        description: Run Markdownlint locally
        entry: mdl
        language: ruby
        files: \.(md|mdown|markdown)$

  # https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
  # https://github.com/pre-commit/mirrors-mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0
    hooks:
      - id: pydocstyle

  # puts the isort.cfg at the root we do not want that
  # https://pypi.org/project/seed-isort-config/
  # - repo: https://github.com/asottile/seed-isort-config
  #   rev: v2.2.0
  #   hooks:
  #     # remember this will place things at the root of the repo
  #     # but running in lint locally places it in the current directory
  #    - id: seed-isort-config
  # does not respect the local arguments
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.2.0
  #   hooks:
  #     - id: isort
  #       args: [--profile=black, -w 79]
  # https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9
        args: [-l 79]
  # check shell scripts you check in
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        args: [--format=json]
